(() => {
  const STORE = 'architect-takehome-v1';
  const initial = {
    page: 'home', mode: 'guided', project: 'Leave Management', status: 'Ready', signedIn: false, userName: 'Vinay Rajpal', userEmail: '',
    projects: [
      { name: 'Leave Management', desc: 'A simple way for teams to request and approve time off.', status: 'Preview ready', updated: 'Just now', icon: '◫' },
      { name: 'Customer feedback hub', desc: 'Collect, organize, and respond to customer feedback.', status: 'Draft', updated: 'Yesterday', icon: '◌' },
      { name: 'Field service dashboard', desc: 'A dispatch view for teams working across locations.', status: 'Draft', updated: 'Sep 18', icon: '⌘' }
    ], messages: [], version: 1, addedLeave: false, activeTab: 'Preview', buildRunning: false, buildStep: 0,
    githubConnected: false, selectedRepo: '', deployState: 'idle', agentRan: false, agents: [], selectedAgent: 0, modal: '', previewRole: 'employee', leaveStatus: 'none'
  };
  let state;
  try { state = { ...initial, ...JSON.parse(localStorage.getItem(STORE) || '{}') }; }
  catch { state = { ...initial }; }
  if (!Array.isArray(state.messages)) state.messages = [];
  const $ = (sel, root = document) => root.querySelector(sel);
  const app = $('#app');
  let toastTimer;
  const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function save() { localStorage.setItem(STORE, JSON.stringify(state)); }
  function notify(msg) { const t=$('#toast'); t.textContent=msg; t.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>t.classList.remove('show'),2500); }
  function setPage(page) { state.page=page; save(); render(); }
  function sidebar() {
    const nav=[['home','⌂','Projects'],['templates','▦','Templates'],['agents','⌘','Agents']];
    const projectNav=[['builder','◈','Build'],['data','▤','Data & integrations'],['github','⑂','GitHub'],['deploy','⇧','Deployments'],['history','◷','History'],['settings','⚙','Settings']];
    return `<aside class="sidebar"><div class="brand"><span class="brand-mark">A</span><span class="brand-name">architect</span></div><div class="workspace-chip"><span class="workspace-avatar">N</span><span>Northstar Studio　⌄</span></div><div class="nav-label">Workspace</div><nav class="nav">${nav.map(([id,ic,label])=>navItem(id,ic,label)).join('')}</nav><div class="nav-label" style="margin-top:23px">Project</div><nav class="nav">${projectNav.map(([id,ic,label])=>navItem(id,ic,label)).join('')}</nav><div class="nav-spacer"></div><div class="side-bottom"><button class="nav-btn" data-action="help"><span class="nav-icon">?</span><span class="nav-text">Help & feedback</span></button><div class="user-row"><span class="user-dot">VR</span><span class="user-meta">${esc(state.userName)}<small>${esc(state.userEmail||'Personal workspace')}</small></span><button class="btn small" data-action="sign-out" aria-label="Sign out">↪</button></div></div></aside>`;
  }
  function navItem(id, icon, label) { return `<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span><span class="nav-text">${label}</span></button>`; }
  function topbar() {
    const label=state.page==='home'?'Projects':state.project;
    return `<header class="topbar"><div class="crumb">Northstar Studio <span class="muted">/</span> <strong>${esc(label)}</strong></div><div class="top-actions"><div class="mode-switch"><button data-mode="guided" class="${state.mode==='guided'?'selected':''}">Guided</button><button data-mode="developer" class="${state.mode==='developer'?'selected':''}">Developer</button></div><button class="btn small ghost" data-action="help">? Help</button></div></header>`;
  }
  function shell(content) { app.innerHTML=`<div class="app-shell">${sidebar()}<main class="main">${topbar()}${content}</main></div><div id="modal-root"></div>`; }
  function authPage() {
    app.innerHTML=`<main class="auth-screen"><section class="auth-story"><div class="brand"><span class="brand-mark">A</span><span class="brand-name">architect</span></div><div class="auth-story-copy"><div class="eyebrow">From idea to owned software</div><h1>Build with a clear path from the first prompt to production.</h1><p>Architect keeps the plan, working preview, source changes and release checks connected, so people can start simply and go deeper when they need to.</p><div class="auth-proof"><span>01 · Agree on scope</span><span>02 · Explore a working slice</span><span>03 · Review before shipping</span></div></div><div class="auth-foot">A workspace for builders at every level.</div></section><section class="auth-form-wrap"><form class="auth-form" id="auth-form"><div class="eyebrow">Welcome to Architect 2.0</div><h2>Sign in to your workspace</h2><p>Use the demo sign-in to explore the complete product flow.</p><label for="auth-name">Your name</label><input class="field" id="auth-name" autocomplete="name" placeholder="Vinay Rajpal" value="${esc(state.userName)}" required><label for="auth-email">Work email</label><input class="field" id="auth-email" type="email" autocomplete="email" placeholder="you@company.com" required><label for="auth-password">Password</label><input class="field" id="auth-password" type="password" autocomplete="current-password" placeholder="Any password for this demo" required><button class="btn primary auth-submit" type="submit">Continue to workspace →</button><div class="auth-divider">or</div><button class="btn auth-submit" type="button" data-action="demo-google">Continue with Google <span class="pill">Demo</span></button><div class="inline-note">Demo authentication is stored in this browser only. No account or password is sent to a server.</div><small>By continuing, you agree to the demo workspace experience.</small></form></section></main>`;
  }
  function homePage() {
    shell(`<section class="page"><div class="hero-card"><div class="hero-copy"><div class="eyebrow">Your workspace</div><div class="hero-title">Good ideas deserve a clear path to working software.</div><p>Start with a prompt, bring an existing project, or pick up where your team left off. Your plan, preview, and changes stay connected.</p><button class="btn primary" data-action="new-project">＋　New project</button></div><div class="hero-orbit"><div class="orbit-ring"></div><div class="orbit-ring two"></div><div class="orbit-core">A</div></div></div><div class="section-row"><h2>Recent projects</h2><span>${state.projects.length} projects</span></div><div class="project-grid">${state.projects.map(p=>`<article class="project-card" data-open-project="${esc(p.name)}"><div class="project-top"><span class="project-icon">${p.icon}</span><span class="status ${p.status==='Draft'?'neutral':''}">${esc(p.status)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><div class="project-foot"><span>Updated ${esc(p.updated)}</span><span>Open project →</span></div></article>`).join('')}</div><div class="section-row"><h2>Start something new</h2><span>Choose the path that fits your work</span></div><div class="start-grid"><article class="start-card" data-action="new-project"><span class="start-icon">✳</span><h3>Describe an idea</h3><p>Start with what the application should help someone do.</p></article><article class="start-card" data-page="github"><span class="start-icon">⑂</span><h3>Import a repository</h3><p>Bring an existing project in and understand it before changing anything.</p></article><article class="start-card" data-page="templates"><span class="start-icon">▦</span><h3>Explore a starting point</h3><p>Use a practical example as a base, then shape it to your needs.</p></article></div></section>`);
  }
  function createPage() {
    shell(`<section class="page"><div class="page-head"><div><div class="eyebrow">New project</div><h1>What are you working on?</h1><p class="page-sub">Start with the user and the problem. Architect will help define a first useful version.</p></div><button class="btn" data-page="home">← Back to projects</button></div><div class="project-start-layout"><div class="panel"><label class="form-label" for="project-prompt">What should this application help someone do?</label><textarea class="field project-prompt" id="project-prompt" placeholder="Example: Help our support team triage incoming requests and track what needs a response."></textarea><div class="field-help">You can begin with a rough idea. We’ll make the first scope reviewable before building.</div><div class="form-row"><label for="project-name">Project name <span class="muted">(optional)</span></label><input class="field" id="project-name" placeholder="e.g. Support triage" /></div><button class="btn primary" data-action="create-from-prompt">Shape the first version →</button></div><div class="start-side"><article class="start-card" data-page="github"><span class="start-icon">⑂</span><h3>Import a repository</h3><p>Bring existing code in and inspect it before changing anything.</p></article><article class="start-card" data-page="templates"><span class="start-icon">▦</span><h3>Start from a template</h3><p>Begin with a focused workflow and sample data.</p></article><div class="inline-note">Your project stays editable: change scope, inspect files, and review deployment readiness as you go.</div></div></div></section>`);
  }
  function planMarkup() { return `<div class="plan-box"><strong>First version · Leave management</strong><ul><li>Employees submit a leave request</li><li>Managers review and approve requests</li><li>Both roles can see request status</li></ul><div class="inline-note">Using sample users and sample data. No real employee records are connected.</div></div><div class="choice-row" style="margin-top:9px"><button class="btn small primary" data-action="approve-plan">Looks good · Build it</button><button class="btn small" data-action="edit-plan">Edit scope</button></div>`; }
  function initialMessages() { return [{role:'user',text:'Build me an employee leave management application.'},{role:'assistant',text:'I’m shaping this into a first useful slice: employees request time off, managers review it, and everyone can see the status. I’ve kept the first version focused so you can test the main workflow quickly.',plan:true}]; }
  function renderMessages() {
    if (!state.messages.length) state.messages=initialMessages();
    return state.messages.map((m,i)=>m.role==='user'?`<div class="message user">${esc(m.text)}</div>`:`<div class="message assistant"><div class="msg-label">ARCHITECT · ${m.kind==='system'?'UPDATE':'PRODUCT PARTNER'}</div><p>${esc(m.text)}</p>${m.plan?planMarkup():''}${m.kind==='done'?`<div class="inline-note">Preview is ready. Sample data only · ${state.version} saved ${state.version===1?'version':'versions'}.</div>`:''}</div>`).join('');
  }
  function leavePreview() {
    const pending=state.leaveStatus==='pending';
    if(state.previewRole==='manager') return `<div class="leave-app"><div class="leave-nav"><div class="leave-brand">northstar <span style="color:#96a4ae;font-weight:400">· people</span></div><div class="leave-user"><button class="btn small" data-action="switch-role">Switch to employee</button><span>Jordan Lee</span><span class="leave-avatar">JL</span></div></div><div class="welcome"><h2>Team leave overview</h2><p>Review requests and keep coverage visible.</p></div><div class="leave-stats"><div class="leave-stat"><small>Pending review</small><strong>${pending?'1':'0'} <span>requests</span></strong><span>Needs a manager decision</span></div><div class="leave-stat"><small>Out this week</small><strong>2 <span>people</span></strong><span>Across your team</span></div><div class="leave-stat"><small>Team coverage</small><strong>Good</strong><span>Based on approved leave</span></div></div><div class="leave-panel" style="margin-top:14px"><div class="leave-panel-head"><strong>Requests to review</strong><span class="small-note">Sample team data</span></div>${pending?`<div class="leave-upcoming"><span>Alex Morgan · Personal leave<small>Oct 12 – Oct 13 · 2 days</small></span><span class="choice-row"><button class="btn small" data-action="decide-request" data-decision="reject">Decline</button><button class="btn small primary" data-action="decide-request" data-decision="approve">Approve</button></span></div>`:`<div class="inline-note">No pending requests. The team is up to date.</div>`}<div class="inline-note">Approval changes the sample preview only; no employee data is stored.</div></div></div>`;
    const rows=state.leaveStatus!=='none'?`<tr><td>Personal leave</td><td>Oct 12 – Oct 13</td><td><span class="leave-tag ${pending?'pending':''}">${pending?'Pending':state.leaveStatus==='approved'?'Approved':'Declined'}</span></td></tr>`:'';
    return `<div class="leave-app"><div class="leave-nav"><div class="leave-brand">northstar <span style="color:#96a4ae;font-weight:400">· people</span></div><div class="leave-user"><button class="btn small" data-action="switch-role">Switch to manager</button><span>Alex Morgan</span><span class="leave-avatar">AM</span></div></div><div class="welcome"><h2>Your time, in balance.</h2><p>Manage time away and keep your team in the loop.</p></div><div class="leave-stats"><div class="leave-stat"><small>Annual leave</small><strong>${state.addedLeave?'17':'19'} <span>days</span></strong><span>of 25 days</span></div><div class="leave-stat"><small>Personal leave</small><strong>5 <span>days</span></strong><span>of 7 days</span></div><div class="leave-stat"><small>Awaiting approval</small><strong>${pending?'1':'0'} <span>requests</span></strong><span>Keep your team updated</span></div></div><div class="leave-content"><div class="leave-panel"><div class="leave-panel-head"><strong>Recent requests</strong><button class="btn small" data-action="request-leave">＋ Request leave</button></div><table class="leave-table"><thead><tr><th>TYPE</th><th>DATES</th><th>STATUS</th></tr></thead><tbody>${rows}<tr><td>Annual leave</td><td>Sep 16 – Sep 18</td><td><span class="leave-tag">Approved</span></td></tr><tr><td>Personal leave</td><td>Aug 04</td><td><span class="leave-tag">Approved</span></td></tr><tr><td>Annual leave</td><td>Jul 11 – Jul 12</td><td><span class="leave-tag">Approved</span></td></tr></tbody></table></div><div class="leave-panel"><div class="leave-panel-head"><strong>Coming up</strong><span class="small-note">Your team</span></div><div class="leave-upcoming"><span>Jamie Lee<small>Annual leave</small></span><span>Oct 03–04</span></div><div class="leave-upcoming"><span>Riley Chen<small>Personal leave</small></span><span>Oct 08</span></div><div class="leave-upcoming"><span>You<small>Annual leave</small></span><span>Sep 16–18</span></div></div></div></div>`;
  }
  function previewTab() { return `<div class="preview-frame"><div class="browser-bar"><i class="browser-dot"></i><i class="browser-dot"></i><i class="browser-dot"></i><div class="url-pill">leave-app.preview.architect.new</div><span class="small-note">↗</span></div>${leavePreview()}</div>`; }
  function buildTab() {
    const steps=['Clarify the request','Create the application shell','Build the leave request flow','Check the preview'];
    const ix=state.buildStep;
    return `<div class="build-progress"><div class="progress-title">${state.buildRunning?'Building your first version':'Your plan is ready'}</div><div class="progress-sub">${state.buildRunning?'Architect is working through the agreed scope. You can inspect the result as it becomes available.':'Review the proposed work before generation starts.'}</div><div class="progress-track"><div class="progress-fill" style="--progress:${state.buildRunning?Math.max(14,ix*27):0}%"></div></div>${steps.map((s,i)=>`<div class="progress-step ${i<ix?'done':''} ${state.buildRunning&&i===ix?'current':''}"><span class="step-icon">${i<ix?'✓':i+1}</span>${s}</div>`).join('')}${state.buildRunning?`<button class="btn small" data-action="cancel-build" style="margin-top:15px">Stop run</button>`:''}</div>`;
  }
  function codeTab() { return `<div class="code-view"><div class="code-header"><span><span class="mono">src/app/</span> · leave-dashboard.tsx</span><span class="pill">Preview file · read-only</span></div><div class="code-content"><span class="line-num">1</span><span class="muted">// Employee leave overview</span>
<span class="line-num">2</span>export function LeaveDashboard() {
<span class="line-num">3</span>  return (
<span class="line-num">4</span>    &lt;WorkspaceLayout title="Your time, in balance."&gt;
<span class="line-num">5</span>      &lt;LeaveBalanceCard days={19} allowance={25} /&gt;
<span class="line-num">6</span>      &lt;RecentRequests items={requests} /&gt;
<span class="line-num">7</span>      &lt;UpcomingTeamLeave /&gt;
<span class="line-num">8</span>    &lt;/WorkspaceLayout&gt;
<span class="line-num">9</span>  );
<span class="line-num">10</span>}</div></div>`; }
  function renderBuilder() {
    const tabs=['Preview',...(state.mode==='developer'?['Files','Checks']:[])];
    const stage=state.buildRunning?buildTab():state.activeTab==='Files'?codeTab():state.activeTab==='Checks'?checksTab():previewTab();
    shell(`<section class="page builder-page"><div class="builder-toolbar"><div class="toolbar-left"><button class="btn small" data-page="home">← Projects</button><span class="mini-sep"></span><span class="builder-title">${esc(state.project)} <small><span class="status">Preview ready</span></small></span></div><div class="toolbar-right"><span class="badge-mock">DEMO PROJECT</span><button class="btn small" data-page="github">⑂ GitHub</button><button class="btn small primary" data-page="deploy">⇧ Deploy</button></div></div><div class="builder-content"><section class="conversation"><div class="conv-head"><strong>Build conversation</strong><span>Plan · Build · Iterate</span></div><div class="messages" id="messages">${renderMessages()}</div><div class="chat-input"><textarea id="prompt-input" placeholder="Describe a change or ask a question…" aria-label="Describe a change"></textarea><div class="chat-input-foot"><small>Enter to send · Shift + Enter for a new line</small><button class="btn primary small" data-action="send-prompt">Send ↑</button></div></div></section><section class="workspace-stage"><div class="stage-tabs">${tabs.map(t=>`<button class="tab-btn ${state.activeTab===t?'active':''}" data-tab="${t}">${t}</button>`).join('')}<span style="flex:1"></span><span class="small-note">${state.buildRunning?'Run in progress':'Local preview'}</span></div><div class="stage-body">${stage}</div></section></div></section>`);
    const messages=$('#messages'); if(messages) messages.scrollTop=messages.scrollHeight;
  }
  function checksTab() { return `<div class="panel" style="width:min(660px,100%)"><div class="eyebrow">Latest checks · version ${state.version}</div><h2 style="font-size:14px;margin:0">Core leave flow</h2><div class="deploy-check"><span class="check">✓</span><span>Employee can view leave balance</span><span class="status" style="margin-left:auto">Passed</span></div><div class="deploy-check"><span class="check">✓</span><span>Leave request appears in recent requests</span><span class="status" style="margin-left:auto">Passed</span></div><div class="deploy-check"><span class="check">✓</span><span>Manager can review pending requests</span><span class="status" style="margin-left:auto">Passed</span></div><p class="small-note">Demo checks are scripted; this take-home does not execute generated code.</p></div>`; }
  function agentsPage() {
    const builtins=[{name:'Leave request reviewer',purpose:'Reviews requests against policy'},{name:'Policy assistant',purpose:'Answers questions from team policy'}];const list=[...builtins,...state.agents];const selected=list[state.selectedAgent]||builtins[0];
    shell(`<section class="page"><div class="page-head"><div><div class="eyebrow">Project capability</div><h1>Agents</h1><p class="page-sub">Define what an agent does, what it can access, and how you know it worked.</p></div><button class="btn primary" data-action="new-agent">＋ New agent</button></div><div class="agent-grid"><div class="agent-list">${list.map((a,i)=>`<button class="agent-item ${state.selectedAgent===i?'active':''}" data-agent-index="${i}"><strong>${esc(a.name)}</strong><small>${esc(a.purpose)}</small></button>`).join('')}</div><div class="panel agent-detail"><div style="display:flex;justify-content:space-between;align-items:center"><div><span class="eyebrow">Agent configuration · ${state.selectedAgent<2?'v1':'Draft'}</span><h2>${esc(selected.name)}</h2></div><span class="status neutral">${state.selectedAgent<2?'Example':'Draft'}</span></div><p>${esc(selected.description||'Reviews a submitted leave request against configured rules and returns a recommendation. It cannot take external actions without human approval.')}</p><div class="section-row"><h2>Allowed tools</h2><span>Least privilege</span></div><div class="tool-row"><span>Read project knowledge</span><span class="status">Read only</span></div><div class="tool-row"><span>Read connected data</span><span class="status">Read only</span></div><div class="tool-row"><span>Write or send externally</span><span class="status amber">Human approval</span></div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:17px"><span class="small-note">Framework · Choose in a production setup</span><button class="btn primary small" data-action="run-agent">${state.agentRan?'Run again':'Run test case'}</button></div>${state.agentRan?`<div class="trace"><strong>TEST RUN · SIMULATED</strong><br/>1. Loaded the selected agent's allowed context<br/>2. Checked the sample request against its instructions<br/>3. Returned a recommendation<br/>4. No external action taken · awaiting a person</div>`:''}<div class="inline-note">Tool access is visible before a run. Production agents need scoped credentials, execution limits, versioning, and observable tool results.</div></div></div></section>`);
  }
  function githubPage() {
    const repos=[['northstar/leave-app','Next.js · TypeScript','Updated 2 hours ago'],['northstar/team-portal','React · Vite','Updated yesterday'],['vinay/side-project','Unsupported framework · read-only import','Updated Sep 18']];
    shell(`<section class="page"><div class="page-head"><div><div class="eyebrow">Project source</div><h1>GitHub</h1><p class="page-sub">Connect a repository when you’re ready to own and collaborate on the code.</p></div><span class="${state.githubConnected?'status':'status neutral'}">${state.githubConnected?'Connected':'Not connected'}</span></div><div class="flow-grid"><div class="panel"><div class="eyebrow">Connection</div><h2 style="font-size:14px;margin:0">${state.githubConnected?'GitHub account linked':'Connect your account'}</h2><p class="page-sub" style="line-height:1.7">${state.githubConnected?'Repository access is simulated in this prototype. No GitHub account has been authorized.':'In the real product, you would choose repository access and review the requested permissions on GitHub.'}</p><button class="btn ${state.githubConnected?'':'primary'}" data-action="connect-github">${state.githubConnected?'Disconnect demo account':'Connect GitHub (demo)'}</button><div class="inline-note">Demo mode: this button does not access GitHub or authorize an account.</div></div><div class="panel"><div class="eyebrow">Repository selection</div><h2 style="font-size:14px;margin:0">Choose a repository</h2><p class="page-sub">A demo repository list. Select one to see the import review.</p>${repos.map(([name,info,date])=>`<div class="repo-row" data-repo="${esc(name)}"><span>⑂　${esc(name)}<small>${esc(info)} · ${esc(date)}</small></span><span>→</span></div>`).join('')}${state.selectedRepo?`<div class="inline-note" style="margin-top:12px"><strong>Selected:</strong> ${esc(state.selectedRepo)} · branch <span class="mono">main</span><br/>Detected: Next.js app · package manager pnpm · sample preview available.<br/><button class="btn small" data-action="import-repo" style="margin-top:8px">Review import</button></div>`:''}</div></div><div class="panel" style="margin-top:14px"><div class="eyebrow">Change review</div><div style="display:flex;justify-content:space-between;align-items:center"><div><strong style="font-size:11px">${state.version>1?'1 file changed':'No pending changes'}</strong><div class="small-note" style="margin-top:4px">${state.version>1?'src/app/leave-dashboard.tsx · +8 −2':'Create a small change in the builder to see the review flow.'}</div></div><button class="btn small" data-action="open-diff">View changes</button></div><div class="inline-note">Real integration should use a selected branch and explicit commit/PR action. This prototype does not push code.</div></div></section>`);
  }
  function dataPage() {
    shell(`<section class="page"><div class="page-head"><div><div class="eyebrow">Project configuration</div><h1>Data & integrations</h1><p class="page-sub">See what is connected and what the preview is using.</p></div><button class="btn" data-page="builder">← Back to build</button></div><div class="flow-grid"><div class="panel"><div class="eyebrow">Data source</div><h2 style="font-size:14px;margin:0">Sample data</h2><p class="page-sub" style="line-height:1.7">The leave-management preview uses in-browser sample data. Requests you create are for demonstration only and are not stored in a shared database.</p><div class="deploy-check"><span class="check">✓</span><span>Preview data available</span><span class="status" style="margin-left:auto">Ready</span></div><div class="deploy-check"><span class="check">✓</span><span>Persistent database</span><span class="status neutral" style="margin-left:auto">Not connected</span></div><button class="btn" data-action="connect-database" style="margin-top:13px">Connect a database (demo)</button></div><div class="panel"><div class="eyebrow">Environment variables</div><h2 style="font-size:14px;margin:0">App configuration</h2><p class="page-sub" style="line-height:1.7">Secret values should be configured in the deployment environment. Architect should only show whether a required key is present.</p><div class="tool-row"><span class="mono">DATABASE_URL</span><span class="status neutral">Not configured</span></div><div class="tool-row"><span class="mono">AUTH_SECRET</span><span class="status neutral">Not configured</span></div><div class="inline-note">Never paste a production secret into the conversation or commit it to Git.</div></div></div><div class="panel" style="margin-top:14px"><div class="eyebrow">Integrations</div><h2 style="font-size:14px;margin:0 0 9px">Add a connection when a workflow needs one</h2><div class="start-grid"><div class="repo-row" data-action="connect-database">▤　Postgres database　<span class="pill">Demo setup</span></div><div class="repo-row" data-action="connect-database">✉　Email provider　<span class="pill">Not connected</span></div><div class="repo-row" data-page="github">⑂　GitHub　<span class="pill">${state.githubConnected?'Connected (demo)':'Not connected'}</span></div></div></div></section>`);
  }
  function deployPage() {
    let main='';
    if(state.deployState==='idle') main=`<div class="deploy-stage"><div class="panel"><div class="eyebrow">Production readiness</div><h2 style="font-size:15px;margin:0">Before this app goes live</h2><p class="page-sub" style="line-height:1.7">Review the current setup. This prototype simulates deployment of the generated leave app; the take-home website is deployed separately.</p><div class="deploy-check"><span class="check">✓</span><span>Preview responds</span><span class="status" style="margin-left:auto">Ready</span></div><div class="deploy-check"><span class="check warn">!</span><span>Persistent database</span><span class="status amber" style="margin-left:auto">Sample data</span></div><div class="deploy-check"><span class="check warn">!</span><span>Authentication and access rules</span><span class="status amber" style="margin-left:auto">Not configured</span></div><div class="deploy-check"><span class="check">✓</span><span>Source changes reviewed</span><span class="status" style="margin-left:auto">Ready</span></div><div class="inline-note">This demo is not production-ready: it has sample data and no real employee authentication.</div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:16px"><span class="small-note">Target · Architect preview hosting (simulated)</span><button class="btn primary" data-action="deploy-start">Deploy demo app →</button></div></div></div>`;
    else if(state.deployState==='running') main=`<div class="deploy-stage"><div class="panel"><div class="eyebrow">Deployment in progress</div><h2 style="font-size:15px;margin:0">Preparing your preview deployment</h2><div class="progress-track"><div class="progress-fill" style="--progress:62%"></div></div><div class="deploy-check"><span class="check">✓</span><span>Readiness checks</span><span class="status" style="margin-left:auto">Done</span></div><div class="deploy-check"><span class="check">✓</span><span>Build application</span><span class="status" style="margin-left:auto">Done</span></div><div class="deploy-check"><span class="check warn">…</span><span>Publish preview URL</span><span class="status amber" style="margin-left:auto">Running</span></div><div class="small-note" style="margin-top:10px">Simulated deployment · no external service called</div></div></div>`;
    else if(state.deployState==='live') main=`<div class="deploy-stage"><div class="deploy-live"><strong>Preview deployment is ready</strong><p class="page-sub">Version ${state.version} · simulated environment</p><a href="#" data-action="open-preview">leave-app.preview.architect.new ↗</a><div style="display:flex;gap:7px;margin-top:14px"><button class="btn small" data-action="open-preview">Open preview</button><button class="btn small" data-action="view-logs">View deploy logs</button><button class="btn small" data-action="rollback-deploy">Rollback</button></div></div><div class="trace">12:41:02 · Readiness checks passed<br/>12:41:04 · Build completed<br/>12:41:05 · Preview published<br/>12:41:05 · No live service was contacted (demo)</div></div>`;
    else main=`<div class="deploy-stage"><div class="panel"><div class="eyebrow">Deployment failed</div><h2 style="font-size:15px;margin:0">Missing production configuration</h2><p class="page-sub" style="line-height:1.7">The demo is showing a recoverable failure: a persistent database and authentication are not configured. The previous version remains available.</p><div class="inline-note">In production, show the failing step and log excerpt, then let the user configure the missing values and retry.</div><div style="display:flex;gap:8px;margin-top:14px"><button class="btn" data-page="data">Review configuration</button><button class="btn primary" data-action="deploy-retry">Retry demo deploy</button></div></div></div>`;
    shell(`<section class="page"><div class="page-head"><div><div class="eyebrow">Ship safely</div><h1>Deployments</h1><p class="page-sub">Understand what’s ready, what’s missing, and which version is live.</p></div><button class="btn" data-page="builder">← Back to build</button></div>${main}</section>`);
  }
  function historyPage() {
    const items=[{v:state.version,label:'Added remaining leave days to dashboard',when:'Just now',current:true},{v:1,label:'Initial leave management workflow',when:'Today',current:state.version===1}];
    shell(`<section class="page"><div class="page-head"><div><div class="eyebrow">Project history</div><h1>Versions</h1><p class="page-sub">A recovery point after each meaningful change.</p></div><button class="btn" data-page="builder">← Back to build</button></div><div class="panel">${items.map(x=>`<div class="history-row"><span class="history-pin"></span><span><strong>v${x.v} · ${esc(x.label)}</strong><small>${x.when} · ${x.current?'Current version':'Checkpoint'}${x.v>1?' · 1 file changed':''}</small></span>${x.current?'<span class="status">Current</span>':`<button class="btn small" data-action="restore-version" data-version="${x.v}">Restore</button>`}</div>`).join('')}<div class="inline-note">Prototype history restores the visible preview state only. A real implementation also needs source-control checkpoints.</div></div></section>`);
  }
  function templatesPage() {
    shell(`<section class="page"><div class="page-head"><div><div class="eyebrow">Start from a useful pattern</div><h1>Templates</h1><p class="page-sub">Templates should accelerate a job, not lock you into a stack.</p></div><button class="btn" data-page="home">← Projects</button></div><div class="project-grid">${[['Leave management','Request and approve time away','✳'],['Support inbox','Triage and respond to incoming requests','◌'],['Operations dashboard','Monitor a team workflow at a glance','▦']].map(([name,desc,icon])=>`<article class="project-card" data-action="use-template" data-template="${esc(name)}"><span class="project-icon">${icon}</span><h3>${esc(name)}</h3><p>${esc(desc)}</p><div class="project-foot"><span>Sample workflow included</span><span>Use template →</span></div></article>`).join('')}</div></section>`);
  }
  function settingsPage() {
    shell(`<section class="page"><div class="page-head"><div><div class="eyebrow">Project configuration</div><h1>Settings</h1><p class="page-sub">Defaults and instructions for this project.</p></div><button class="btn" data-page="builder">← Back to build</button></div><div class="settings-list"><div class="settings-row"><span><strong>Project name</strong><small>Shown in navigation and deployment history.</small></span><button class="btn small" data-action="rename-project">Rename</button></div><div class="settings-row"><span><strong>Build mode</strong><small>Change how much technical detail appears by default.</small></span><span class="pill">${state.mode==='guided'?'Guided':'Developer'}</span></div><div class="settings-row"><span><strong>Framework</strong><small>Detected for this preview project.</small></span><span class="pill">Next.js · demo</span></div><div class="settings-row"><span><strong>Project instructions</strong><small>Keep generated work consistent with team conventions.</small></span><button class="btn small" data-action="edit-instructions">Add instructions</button></div></div></section>`);
  }
  function render() {
    if(!state.signedIn) return authPage();
    if(state.page==='home') return homePage();
    if(state.page==='new') return createPage();
    if(state.page==='builder') return renderBuilder();
    if(state.page==='agents') return agentsPage();
    if(state.page==='github') return githubPage();
    if(state.page==='data') return dataPage();
    if(state.page==='deploy') return deployPage();
    if(state.page==='history') return historyPage();
    if(state.page==='templates') return templatesPage();
    if(state.page==='settings') return settingsPage();
    homePage();
  }
  function addMessage(role,text,extra={}) { state.messages.push({role,text,...extra}); save(); }
  function startBuild() {
    state.buildRunning=true;state.buildStep=0;state.activeTab='Preview';save();render();
    const steps=[1,2,3,4];
    steps.forEach((step,i)=>setTimeout(()=>{
      if(!state.buildRunning)return;
      state.buildStep=step;save();render();
      if(i===steps.length-1){state.buildRunning=false;state.status='Ready';state.version=Math.max(1,state.version);addMessage('assistant','Your first version is ready. Employees can submit a request, managers can review it, and the preview uses sample data.',{kind:'done'});render();notify('Preview is ready to explore');}
    },700*(i+1)));
  }
  function sendPrompt() {
    const field=$('#prompt-input'); if(!field)return;
    const text=field.value.trim();if(!text)return;
    addMessage('user',text);
    const change=/leave days|remaining|balance|days/i.test(text);
    if(change){state.addedLeave=true;state.version+=1;addMessage('assistant','I’ll add a clearer remaining-days summary to the leave balance card. This updates the preview and creates a reviewable project version.',{kind:'system'});state.activeTab='Preview';save();render();notify('Change applied to the demo preview');}
    else {addMessage('assistant','I’ve captured that as a focused follow-up. For this demo, the leave workflow is the active slice. You can ask to show remaining leave days to see an iteration.',{kind:'system'});render();}
  }
  function showModal(title,body,confirmText='Continue',onConfirm=()=>{}) {
    const root=$('#modal-root'); if(!root)return;
    root.innerHTML=`<div class="modal-backdrop" data-action="modal-dismiss"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">${esc(title)}</h2><div>${body}</div><div class="modal-actions"><button class="btn" data-action="modal-cancel">Cancel</button><button class="btn primary" data-action="modal-confirm">${esc(confirmText)}</button></div></div></div>`;
    root.dataset.confirm=String(Date.now()); root._onConfirm=onConfirm;
  }
  document.addEventListener('click',e=>{
    const page=e.target.closest('[data-page]');if(page){setPage(page.dataset.page);return;}
    const mode=e.target.closest('[data-mode]');if(mode){state.mode=mode.dataset.mode;save();render();return;}
    const open=e.target.closest('[data-open-project]');if(open){state.project=open.dataset.openProject;state.page='builder';state.activeTab='Preview';if(!state.messages.length)state.messages=initialMessages();save();render();return;}
    const tab=e.target.closest('[data-tab]');if(tab){state.activeTab=tab.dataset.tab;save();render();return;}
    const agentItem=e.target.closest('[data-agent-index]');if(agentItem){state.selectedAgent=Number(agentItem.dataset.agentIndex);state.agentRan=false;save();render();return;}
    const repo=e.target.closest('[data-repo]');if(repo){state.selectedRepo=repo.dataset.repo;save();render();return;}
    const action=e.target.closest('[data-action]');if(!action)return;
    switch(action.dataset.action){
      case 'new-project':setPage('new');break;
      case 'start-prompt':setPage('new');break;
      case 'create-from-prompt':{const prompt=$('#project-prompt')?.value.trim();if(!prompt){notify('Describe the user problem to get started');$('#project-prompt')?.focus();break;}const name=$('#project-name')?.value.trim()||prompt.split(/[.!?]/)[0].slice(0,36)||'Untitled project';state.project=name;state.messages=[{role:'user',text:prompt},{role:'assistant',text:`Let’s shape a first version around this problem: “${prompt}” Start with the smallest workflow someone can try, then review the scope before building.`,kind:'system'},{role:'assistant',text:'For this prototype, the interactive preview is the leave management example. The project brief above is saved as your starting point; generation for other ideas is not connected.',kind:'system'}];state.projects.unshift({name,desc:prompt.slice(0,90),status:'Brief ready',updated:'Just now',icon:'✳'});state.page='builder';state.activeTab='Preview';save();render();notify('Project brief created');break;}
      case 'approve-plan':addMessage('assistant','Plan approved. I’ll build the employee request flow, manager review, and visible request status using sample data.',{kind:'system'});startBuild();break;
      case 'edit-plan':showModal('Adjust the first version','<p>For this demo, the scope is intentionally small: request time off, manager review, and request status. Tell the builder what to change before generation.</p><textarea class="field" id="scope-edit" rows="3" placeholder="Add or remove a requirement…"></textarea>','Save scope',()=>{const val=$('#scope-edit')?.value?.trim();if(val)addMessage('assistant',`Scope updated: ${val}`,{kind:'system'});render();});break;
      case 'send-prompt':sendPrompt();break;
      case 'request-leave':if(state.leaveStatus==='pending'){notify('A sample request is already waiting for review');}else{state.leaveStatus='pending';state.addedLeave=true;state.version+=1;save();render();notify('Sample leave request submitted');}break;
      case 'switch-role':state.previewRole=state.previewRole==='employee'?'manager':'employee';save();render();break;
      case 'decide-request':state.leaveStatus=action.dataset.decision==='approve'?'approved':'declined';state.version+=1;save();render();notify(`Sample request ${state.leaveStatus}`);break;
      case 'cancel-build':state.buildRunning=false;save();render();notify('Build stopped. Your last preview is unchanged.');break;
      case 'run-agent':state.agentRan=true;save();render();notify('Sample agent test completed');break;
      case 'connect-github':state.githubConnected=!state.githubConnected;if(!state.githubConnected)state.selectedRepo='';save();render();notify(state.githubConnected?'Demo GitHub connection enabled':'Demo connection removed');break;
      case 'import-repo':showModal('Review repository import',`<p><strong>${esc(state.selectedRepo)}</strong> · branch <span class="mono">main</span></p><p>Detected a Next.js project with a package manifest. Import is simulated: no repository files will be read or copied.</p><div class="inline-note">Recommended first step: inspect the project summary and run a preview before asking for changes.</div>`,'Open project',()=>{state.project=state.selectedRepo.split('/').pop();state.messages=[{role:'assistant',text:'Repository import is simulated in this prototype. A real import would scan the selected branch, detect framework and setup, then validate a preview before modifications.',kind:'system'}];state.page='builder';save();render();});break;
      case 'deploy-start':state.deployState='running';save();render();setTimeout(()=>{if(state.deployState==='running'){state.deployState='live';save();render();notify('Demo deployment is ready');}},1800);break;
      case 'deploy-retry':state.deployState='running';save();render();setTimeout(()=>{if(state.deployState==='running'){state.deployState='live';save();render();notify('Demo deployment is ready');}},1400);break;
      case 'rollback-deploy':state.deployState='idle';save();render();notify('Returned to the readiness review');break;
      case 'open-preview':state.page='builder';state.activeTab='Preview';save();render();break;
      case 'view-logs':notify('Deployment logs are shown below the result');break;
      case 'restore-version':if(Number(action.dataset.version)===1){state.version=1;state.addedLeave=false;save();render();notify('Restored the initial preview version');}break;
      case 'connect-database':showModal('Database connection (demo)','<p>This prototype uses sample data stored in the browser. A real connection would request access to a database and validate its schema.</p><div class="inline-note">No database credentials are collected here.</div>','Understood',()=>notify('Database setup remains simulated'));break;
      case 'open-diff':state.page='builder';state.mode='developer';state.activeTab='Files';save();render();break;
      case 'new-agent':showModal('Create an agent','<div class="form-row"><label for="agent-name">Agent name</label><input id="agent-name" class="field" placeholder="e.g. Support triage assistant" required></div><div class="form-row"><label for="agent-purpose">What should it do?</label><textarea id="agent-purpose" class="field" rows="3" placeholder="Describe the task and the result it should return."></textarea></div><div class="form-row"><label for="agent-framework">Framework</label><select id="agent-framework" class="field"><option>Framework independent</option><option>Lyzr</option><option>LangGraph</option><option>CrewAI</option><option>OpenAI Agents SDK</option><option>Custom adapter</option></select></div><div class="inline-note">New agents begin in draft with read-only tools. Add write actions only with explicit review.</div>','Create draft',()=>{const name=$('#agent-name')?.value.trim();if(!name){notify('Add a name for this agent');return false;}const purpose=$('#agent-purpose')?.value.trim()||'Returns a recommendation for a person to review.';state.agents.push({name,purpose,description:`${purpose} Framework: ${$('#agent-framework')?.value||'Framework independent'}. Draft only; no tools are connected.`});state.selectedAgent=state.agents.length+1;state.agentRan=false;save();render();notify('Agent draft created');});break;
      case 'use-template':state.project=action.dataset.template;state.page='builder';state.messages=initialMessages();save();render();break;
      case 'rename-project':showModal('Rename project','<div class="form-row"><label for="rename-input">Project name</label><input id="rename-input" class="field" value="'+esc(state.project)+'"></div>','Save name',()=>{const v=$('#rename-input')?.value?.trim();if(v)state.project=v;save();render();notify('Project renamed');});break;
      case 'edit-instructions':showModal('Project instructions','<p>Instructions guide future changes in this project.</p><textarea class="field" rows="3" placeholder="Use accessible labels and keep the leave workflow simple."></textarea>','Save instructions',()=>notify('Instructions saved for this demo'));break;
      case 'help':showModal('A workspace built around your project','<p>Start in Guided mode for a clear prompt-to-preview flow. Switch to Developer mode to inspect files, checks, and changes.</p><p class="small-note">This take-home includes simulated AI generation, GitHub authorization, agent execution, database connection, and generated-app deployment.</p>','Got it',()=>{});break;
      case 'demo-google':state.userName='Vinay Rajpal';state.userEmail='vinay@example.com';state.signedIn=true;save();render();notify('Demo workspace ready');break;
      case 'sign-out':state.signedIn=false;save();render();break;
      case 'modal-cancel':$('#modal-root').innerHTML='';break;
      case 'modal-confirm':{const root=$('#modal-root');const keepOpen=root?._onConfirm?.()===false;if(!keepOpen&&$('#modal-root'))$('#modal-root').innerHTML='';break;}
      case 'modal-dismiss':if(e.target===action)$('#modal-root').innerHTML='';break;
      default:notify('This action is represented in the prototype flow');
    }
  });
  document.addEventListener('submit',e=>{if(e.target.id==='auth-form'){e.preventDefault();const email=$('#auth-email')?.value.trim();const name=$('#auth-name')?.value.trim();if(!email||!name)return;state.userEmail=email;state.userName=name;state.signedIn=true;save();render();notify('Welcome to Architect');}});
  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&e.target.id==='prompt-input'){e.preventDefault();sendPrompt();}if(e.key==='Escape'&&$('#modal-root'))$('#modal-root').innerHTML='';});
  render();
})();
